# Generated by Django 4.1.5 on 2023-01-21 23:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_data(apps, schema_editor):
    AccountType = apps.get_model('core', 'AccountType')
    AccountType.objects.create(id=1, type='SAVINGS')
    AccountType.objects.create(id=2, type='CHECKING')

    TransactionType = apps.get_model('core', 'TransactionType')
    TransactionType.objects.create(id=1, type='DEPOSIT', operator='+')
    TransactionType.objects.create(id=2, type='WITHDRAW', operator='-')

    TransactionStatus = apps.get_model('core', 'TransactionStatus')
    TransactionStatus.objects.create(id=1, status='PENDING')
    TransactionStatus.objects.create(id=2, status='SUCCESS')
    TransactionStatus.objects.create(id=3, status='FAILED')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
                ('operator', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='error',
            field=models.CharField(blank=True, choices=[('without_founds', 'WITHOUT FOUNDS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accounttype'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transactiontype'),
        ),
        migrations.RunPython(create_data)
    ]
